name: zap_stream_flutter
description: "zap.stream"
publish_to: "none"
version: 0.8.1+11

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  ndk: ^0.3.2
  ndk_objectbox: ^0.2.3
  ndk_amber: ^0.3.0
  amberflutter: ^0.0.9
  ndk_rust_verifier: ^0.3.1
  go_router: ^15.1.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  wakelock_plus: ^1.3.2
  rxdart: ^0.28.0
  crypto: ^3.0.6
  convert: ^3.1.2
  collection: ^1.19.1
  video_player: ^2.9.5
  clipboard: ^0.1.3
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1
  chewie: ^1.11.3
  image_picker: ^1.1.2
  emoji_picker_flutter: ^4.3.0
  bech32: ^0.2.2
  flutter_markdown_plus: ^1.0.3
  share_plus: ^11.0.0
  duration: ^4.0.3
  slang: ^4.7.1
  slang_flutter: ^4.7.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  http: ^1.4.0
  flutter_local_notifications: ^19.2.1
  flutter_dotenv: ^5.2.1
  protocol_handler: ^0.2.0

dependency_overrides:
  ndk:
    git:
      url: https://github.com/relaystr/ndk
      path: packages/ndk
      ref: 6242899ee4ff7f65e57518d4eb29e2a253b3c4da
  ndk_objectbox:
    git:
      url: https://github.com/relaystr/ndk
      path: packages/objectbox
      ref: 6242899ee4ff7f65e57518d4eb29e2a253b3c4da
  ndk_amber:
    git:
      url: https://github.com/relaystr/ndk
      path: packages/amber
      ref: 6242899ee4ff7f65e57518d4eb29e2a253b3c4da
  emoji_picker_flutter:
    git:
      url: https://github.com/nostrlabs-io/emoji_picker_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - ".env"
    - ".env.development"
    - "assets/svg/"
    - "assets/logo.png"
    - "assets/category/"
