name: zap_stream_flutter
description: "zap.stream"
publish_to: 'none'
version: 0.2.2+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  ndk: ^0.3.2
  ndk_objectbox: ^0.2.3
  ndk_amber: ^0.3.0
  amberflutter: ^0.0.9
  ndk_rust_verifier: ^0.3.1
  go_router: ^15.1.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  wakelock_plus: ^1.3.2
  rxdart: ^0.28.0
  crypto: ^3.0.6
  convert: ^3.1.2
  collection: ^1.19.1
  video_player: ^2.9.5
  clipboard: ^0.1.3
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1
  chewie: ^1.11.3
  image_picker: ^1.1.2
  emoji_picker_flutter: ^4.3.0
  bech32: ^0.2.2
  intl: ^0.20.2

dependency_overrides:
  ndk:
    git:
      url: https://github.com/relaystr/ndk
      path: packages/ndk
      ref: bbf2aa9c2468b2301de65734199649d56bb0fd74

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/svg/"
    - "assets/logo.png"