// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd9GBruNVBv2qrwv0CGvYeby0ALtTlFKk',
    appId: '1:953923151748:web:f04633c33f9343b19e9fd1',
    messagingSenderId: '953923151748',
    projectId: 'nostrlabs',
    authDomain: 'nostrlabs.firebaseapp.com',
    storageBucket: 'nostrlabs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdpxIN8DR1-mh8MCjHU0mDtaUAk6xda6w',
    appId: '1:953923151748:android:8536cdc7f75edc9f9e9fd1',
    messagingSenderId: '953923151748',
    projectId: 'nostrlabs',
    storageBucket: 'nostrlabs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByygErXpki6Q7NXOXTHbRgg3-Tw-KCVO0',
    appId: '1:953923151748:ios:30ec9a230e55fe139e9fd1',
    messagingSenderId: '953923151748',
    projectId: 'nostrlabs',
    storageBucket: 'nostrlabs.firebasestorage.app',
    iosBundleId: 'io.nostrlabs.zapStreamFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByygErXpki6Q7NXOXTHbRgg3-Tw-KCVO0',
    appId: '1:953923151748:ios:19516d42a1cc02229e9fd1',
    messagingSenderId: '953923151748',
    projectId: 'nostrlabs',
    storageBucket: 'nostrlabs.firebasestorage.app',
    iosBundleId: 'com.example.zapStreamFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd9GBruNVBv2qrwv0CGvYeby0ALtTlFKk',
    appId: '1:953923151748:web:6b9a6be6798644909e9fd1',
    messagingSenderId: '953923151748',
    projectId: 'nostrlabs',
    authDomain: 'nostrlabs.firebaseapp.com',
    storageBucket: 'nostrlabs.firebasestorage.app',
  );
}
