name: build
on: push
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build appbundle
      - run: flutter build apk --split-per-abi
      - uses: actions/upload-artifact@v4
        with:
          name: "freeflow_release.aab"
          path: "build/app/outputs/bundle/release/app-release.aab"
      - uses: actions/upload-artifact@v4
        with:
          name: "app-arm64-v8a-release.apk"
          path: "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
      - uses: actions/upload-artifact@v4
        with:
          name: "app-armeabi-v7a-release.apk"
          path: "build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk"
      - uses: actions/upload-artifact@v4
        with:
          name: "app-x86_64-release.apk"
          path: "build/app/outputs/flutter-apk/app-x86_64-release.apk"
  ios:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build ios --no-codesign