name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*
jobs:
  android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - name: Build apk
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_SHA256: ${{ secrets.KEYSTORE_SHA256 }}
        run: flutter build apk --split-per-abi --release
      - uses: actions/upload-artifact@v4
        with:
          name: "app-arm64-v8a-release.apk"
          path: "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
      - uses: actions/upload-artifact@v4
        with:
          name: "app-armeabi-v7a-release.apk"
          path: "build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk"
      - uses: actions/upload-artifact@v4
        with:
          name: "app-x86_64-release.apk"
          path: "build/app/outputs/flutter-apk/app-x86_64-release.apk"
      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk